### ISSUE TITLE
Calling a Job from controller

### ISSUE THREAD

**Issue by Katalyst33** [xpresserjs/framework#46]
First of all i would like to say i love xpresser Framework very much. it has made me a better node js developer.

It would be really cool, if i can run a job from a controller.

**Comment by trapcodeio** [comment]
@Katalyst33 this feature has been added to the [`beta`](https://www.npmjs.com/package/xpresser/v/beta) version of xpresser and will be pushed to **main** version **after 3 days** of rigorous tests.

`npm i xpresser@beta` **OR** `yarn add xpresser@beta`


#### Javascript
```js
const JobHelper = require("xpresser/dist/src/Console/JobHelper");
```

#### Typescript
```ts
import JobHelper from "xpresser/dist/src/Console/JobHelper";
````

#### Usage
Dispatch a job from anywhere in your project, E.g
```ts
// `xjs @ seed/users` will be
JobHelper.dispatch("seed/users") 

// => xjs @ seed/users subscribers 10
JobHelper.dispatch("seed/users", ["subscribers", 10]) 
```

Do try and it out and give me your feedback if it works as expected.

**Comment by Katalyst33** [comment]
wow, i wasnt expecting an update so soon 🤟, 
nice to know arguments are supported too.
i was able to set it up on my first try..
worked just as i aspected.

here is my code sample.


SeedUser.ts
`
import JobHelper from "xpresser/src/Console/JobHelper";

/**
 *  Job: SeedUsers
 */
export = {
  // Job Handler
  async handler(args: string[], job: JobHelper): Promise<any> {
    // Your Job Here

    console.log(args[0], args[1]);

    console.log("Users have been Seeded");
    // End current job process.
    return job.end();
  },
};

`

Seeder Controller
`
import { ControllerClass } from "xpresser";
import { Http } from "xpresser/types/http";
import JobHelper from "xpresser/dist/src/Console/JobHelper";

/**
 * SeederController
 */
class SeederController extends ControllerClass {
  /**
   * Example controller action.
   * @param {Http} http
   */

  seed(http: Http) {
    // `xjs @ seed/users`

    JobHelper.dispatch("SeedUsers");

    // `xjs @ seed/users subscribers 10`
    JobHelper.dispatch("SeedUsers", ["subscribers", 10]);

    return http.send({
      route: http.route,
    });
  }
}

export = SeederController;

`


thank you for your fast response.
remain awesome
